server {
    listen 8080; # Puerto seguro 'unprivileged' que configuramos antes
    
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html; # Evita errores 404 al recargar rutas
    }

    # PROXY INVERSO PARA EL BACKEND DE VENTAS (Mapea /api/v1/ventas)
    location /api/v1/ventas {
        proxy_pass http://10.0.2.201:8080; # ⚠️ REEMPLAZA POR LA IP PRIVADA REAL DE TU EC2 BACKEND
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # PROXY INVERSO PARA EL BACKEND DE DESPACHOS (Mapea /api/v1/despachos si corresponde)
    location /api/v1/despachos {
        proxy_pass http://10.0.2.201:8081; # ⚠️ REEMPLAZA POR LA IP PRIVADA REAL DE TU EC2 BACKEND
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}