name: Deploy Innovatech Frontend to EKS

on:
  push:
    branches:
      - deploy # Cambia esto si usas la rama main o master

env:
  AWS_REGION: us-east-1
  EKS_CLUSTER_NAME: devopseks
  ECR_REGISTRY: 522965979796.dkr.ecr.us-east-1.amazonaws.com

jobs:
  build-and-deploy:
    name: Build, Push & Deploy Frontend to EKS
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout del código
        uses: actions/checkout@v3

      - name: 2. Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: 3. Login en Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: 4. Construir y Subir Imagen a ECR
        run: |
          docker build -t ${{ env.ECR_REGISTRY }}/innovatech-frontend:${{ github.sha }} -t ${{ env.ECR_REGISTRY }}/innovatech-frontend:latest -f Dockerfile .
          docker push ${{ env.ECR_REGISTRY }}/innovatech-frontend:${{ github.sha }}
          docker push ${{ env.ECR_REGISTRY }}/innovatech-frontend:lates

      - name: 5. Conectar GitHub Actions al Clúster EKS
        run: |
          aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }} --region ${{ env.AWS_REGION }}

      - name: 6. Desplegar Frontend en Kubernetes
        run: |
          kubectl apply -f ./k8s/
          kubectl rollout restart deployment/frontend-deployment